### ISSUE TITLE
Empty files produced by kevlar split cause crash of kevlar assemble

### ISSUE THREAD

**Issue by serosko** [kevlar-dev/kevlar#374]
I am trying to run the [tutorial workflow](https://kevlar.readthedocs.io/en/latest/tutorial.html) with kevlar v0.7+15.gebabd62.
The Snakemake workflow stops when coming to the rule "assemble", throwing the following error message:
```
Traceback (most recent call last):
  File "/fast/users/roskoscs_c/work/miniconda/envs/kevlar-env/bin/kevlar", line 8, in <module>
    sys.exit(main())
  File "/fast/users/roskoscs_c/work/miniconda/envs/kevlar-env/lib/python3.6/site-packages/kevlar/__main__.py", line 30, in main
    mainmethod(args)
  File "/fast/users/roskoscs_c/work/miniconda/envs/kevlar-env/lib/python3.6/site-packages/kevlar/assemble.py", line 58, in main
    for partid, contig in assembler:
  File "/fast/users/roskoscs_c/work/miniconda/envs/kevlar-env/lib/python3.6/site-packages/kevlar/assemble.py", line 30, in assemble
    for partid, partition in partstream:
  File "/fast/users/roskoscs_c/work/miniconda/envs/kevlar-env/lib/python3.6/site-packages/kevlar/seqio.py", line 72, in parse_partitioned_reads
    name = read.name if hasattr(read, 'name') else read.defline
AttributeError: 'NoneType' object has no attribute 'defline'
```
I inspected the 16  possible input files for the rule (partitioned.{i}.augfastx.gz, i=0...15), and noticed that only the files partitioned.0.augfastx.gz - partitioned.4.augfastx.gz contain reads, while the subsequent files don't contain any reads. Only the assemble steps working on the empty files fail.

**Comment by standage** [comment]
Thanks for the report. Did you use the default `"numsplit": 16` in your config file? As you've probably guessed, this is used to split the data and compute some later steps of the workflow in parallel. For 30x human WGS data, this will provide a decent speedup. For a mock 25 Mb genome with 10 *de novo* variants I don't expect it to make any practical difference. Try running it with `"numsplit": 2` (or even 1) and see if that fixes the problem. If so, I'll add a clarifying note to the tutorial.

**Comment by serosko** [comment]
Yes, I found the option after writing the issue and tried it with "numsplit": 4.
Now that I have the results, I can confirm that this fixed the issue.

**Comment by standage** [comment]
Roger that. I'll close this thread once the documentation has been clarified.
