### ISSUE TITLE
kevlar call crashing

### ISSUE THREAD

**Issue by sph35** [kevlar-dev/kevlar#378]
While trying the kevlar tutorial workflow, at kevlar call step it is crashing and throwing the following error: 

```
[[kevlar::call] Loading contigs into memory by partition
Traceback (most recent call last):
  File "/PHShome/sph35/.conda/envs/kevlarClone/bin/kevlar", line 8, in <module>
    sys.exit(main())
  File "/PHShome/sph35/.conda/envs/kevlarClone/lib/python3.7/site-packages/kevlar/__main__.py", line 31, in main
    mainmethod(args)
  File "/PHShome/sph35/.conda/envs/kevlarClone/lib/python3.7/site-packages/kevlar/call.py", line 129, in main
    contigs_by_partition = load_contigs(contigstream)
  File "/PHShome/sph35/.conda/envs/kevlarClone/lib/python3.7/site-packages/kevlar/call.py", line 108, in load_contigs
    for partid, contiglist in contigstream:
  File "/PHShome/sph35/.conda/envs/kevlarClone/lib/python3.7/site-packages/kevlar/seqio.py", line 72, in parse_partitioned_reads
    name = read.name if hasattr(read, 'name') else read.defline
AttributeError: 'NoneType' object has no attribute 'defline'
```

Has anyone else encountered/found a fix for this?

**Comment by standage** [comment]
Sorry for the delayed response. Can you show the the precise commands you ran (starting with `kevlar count`) that led to this error message? How much memory does your computer have?

**Comment by sph35** [comment]
Here are the scripts I ran 
```
#!/bin/bash
#BSUB -J Kevlar_ArrayJob[6]
#BSUB -e /err_files/targz.err
#BSUB -q big
#BSUB -n 1
#BSUB mem=16G
#BSUB swp=16G
#BSUB -sla miket_sc

SOURCE_FILE_1="/kevlar/files_counttable.txt"
SOURCE_FILE_2="/kevlar/files_fastq.txt"

INPUT_1=$(sed -n ''${LSB_JOBINDEX}'p' ${SOURCE_FILE_1})
INPUT_2=$(sed -n ''${LSB_JOBINDEX}'p' ${SOURCE_FILE_2})

filename=$(basename -- "$INPUT_2")
extension="${filename##*.}"
filename="${filename%.fastq}"

OUTPUT=${filename}_novel
source activate kevlar
N_THREADS=$(nproc)
kevlar novel --out ${OUTPUT}_reads.fastq \
    --control-counts /data/talkowski/sphao/projects/kevlar/YM003-C.counttable \
    --case-counts ${INPUT_1} --case ${INPUT_2}

#!/bin/bash
#BSUB -J Kevlar_ArrayJob[6]
#BSUB -o /log_files/kevlarArrayJob04.log
#BSUB -e /files/err_files/targz04.err
#BSUB -q big
#BSUB -n 1
#BSUB mem=64G
#BSUB swp=64G
#BSUB -sla miket_sc

SOURCE_FILE_1="/kevlar/files_novel_reads_filtered.txt"
INPUT_1=$(sed -n ''${LSB_JOBINDEX}'p' ${SOURCE_FILE_1})

filename=$(basename -- "$INPUT_1")
extension="${filename##*.}"
filename="${filename%_novelReadsFiltered}"

OUTPUT=${filename}_partition
source activate kevlar
kevlar partition -o ${OUTPUT} ${INPUT_1}
```
