### ISSUE TITLE
partition, node error

### ISSUE THREAD

**Issue by 17tranap** [kevlar-dev/kevlar#379]
Running from the command line, using the augmented fasta output from the kevlar workflow, I get this error indicating there is no 'node' attribute, and looking through the ReadGraph.py file, there is no node struct declared. I do run pretty close to my RAM capacity, is this the cause?

```
[kevlar] running version 0.7
[kevlar::partition] Loading reads
[kevlar::partition] Reads loaded in 213.59 sec
[kevlar::partition] Building read graph in relaxed mode
[kevlar::partition] Graph built in 71.31 sec
[kevlar::partition] Partition readgraph
Traceback (most recent call last):
  File "/home/user/.local/bin/kevlar", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/kevlar/__main__.py", line 30, in main
    mainmethod(args)
  File "/home/user/.local/lib/python3.6/site-packages/kevlar/partition.py", line 68, in main
    for partnum, part in partitioner:
  File "/home/user/.local/lib/python3.6/site-packages/kevlar/partition.py", line 44, in partition
    for n, part in enumerate(part_iter, 1):
  File "/home/user/.local/lib/python3.6/site-packages/kevlar/readgraph.py", line 144, in partitions
    readstream = [self.get_record(readid) for readid in cc]
  File "/home/user/.local/lib/python3.6/site-packages/kevlar/readgraph.py", line 144, in <listcomp>
    readstream = [self.get_record(readid) for readid in cc]
  File "/home/user/.local/lib/python3.6/site-packages/kevlar/readgraph.py", line 41, in get_record
    return self.node[recordname]['record']
AttributeError: 'ReadGraph' object has no attribute 'node'
```

**Comment by standage** [comment]
Hi @17tranap! I don't think this is an issue with RAM. Could you let me know what version of networkx you have installed? That might be the issue here.

**Comment by 17tranap** [comment]
Thank you for your prompt response. I tried the dev version of kevlar on another system with networkx-2.4 and it worked. It looks like my local python dependencies need to be sorted out.

**Comment by standage** [comment]
Glad you could resolve this!

**Comment by johnsmith2077** [comment]
Encounter the same problem, and I found Graph.node(which is deprecated) has been replaced with Graph.nodes since [networkx-2.4](https://networkx.github.io/documentation/stable/release/release_2.4.html#deprecations), so I downgrade to networkx-2.3 and could solve the problem.
